version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: restapidemo
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=restdemo
      - POSTGRES_USER=junior
      - POSTGRES_DB=restdb
volumes:
  db-data: